print("^2 ================================================================ ")
print("")
print("")
print("^1\t\t   YZK CORE ALPHA")
print("^3\t      Tout est niquel mon pote!")
print("^3\tCore Crée pour le serveur VinityLife")
print("")
print("\t\t^1Crée par YZK#8996")
print("")
print("^2 ================================================================")